/*******************************************************************************
 * realMethods Confidential
 * 
 * 2018 realMethods, Inc.
 * All Rights Reserved.
 * 
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *  
 * Contributors :
 *       realMethods Inc - General Release
 ******************************************************************************/
package com.cloudmigrate.foundational.common.exception;


/**
 * Base class of all Framework checked exceptions.
 * <p>
 * For each instance, a unique identifier is generated by calling:<br>
 * <i>Utility.generateUID()</ii></br>
 * The toString() method includes the host name of the current machine, the uid, and the 
 * exception specific text 
 * <p>
 * @author    realMethods, Inc.
 * @see		  com.cloudmigrate.foundational.common.misc.Utility
 */
public class FrameworkCheckedException extends Exception
{
//************************************************************************    
// Public Methods
//************************************************************************
    /** 
     * Base constructor.
     */
    public FrameworkCheckedException()
    {
        super();   
        
    }

    /** 
     * Constructor with message.
     * @param	message
     */
    public FrameworkCheckedException( String message )
    {
        super( message );   
    }    

    /**
     * Constructor with a Throwable for chained exception.
     * 
     * @param 	exception
     */
    public FrameworkCheckedException( Throwable exception )
    {
    	super( exception );
    }

    /**
     * Constructor with a Throwable for chained exception and a message.
     * @param message 	text of the exception
     * @param exception Throwable that is the prior chained exception.
     */
    public FrameworkCheckedException( String message, Throwable exception )
    {
        // call base class
        super(message, exception);
    }
        
}
